# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0d0d2d084749333de19f0041a5320b4482d35f140b5c28d7b640ca99bbac8ed32a9c411e1d5ba32c60cb4982ce9e897578fc2ae25099ee9ba721b8aceb42bbd

test:
  secret_key_base: 4a949ae66723531d0f3757c98a2c679110a24a0d9d760d0423c64144e20288ba4a50def6c9a0823518862916454476299fd2ce7eb57476909a1db01d27a3015d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
